[package]
name = "codie-discord"
version = "0.1.0"
authors = ["Eli W. Hunter <elihunter173@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
log = "0.4"
simple_logger = "1"
regex = "1"
lazy_static = "1"
futures = "0.3"
anyhow = "1"
futures-util = "0.3"

[dependencies.serenity]
version = "0.9"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "rustls_backend",
]

[dependencies.shiplift]
git = "https://github.com/softprops/shiplift.git"
branch = "master"
default-features = false
features = ["unix-socket", "chrono"]

[dev-dependencies]
# Make test case generation easier
paste = "0.1"
