[package]
name = "codie-discord"
version = "0.1.0"
authors = ["Eli W. Hunter <elihunter173@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.2.21"
log = "0.4"
simple_logger = "1.6.0"
regex = "1.3.9"
lazy_static = "1.4.0"
futures = "0.3.5"
anyhow = "1.0.31"
futures-util = "0.3.5"

[dependencies.serenity]
git = "https://github.com/acdenisSK/serenity"
branch = "await_next"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "rustls_backend",
]

[dependencies.shiplift]
# async-await shiplift from
# https://github.com/softprops/shiplift/pull/191#issuecomment-653848228
git = "https://github.com/elihunter173/shiplift.git"
branch = "update-hyper"
# default-features = false
# features = ["unix-socket", "chrono"]
